chore: revert

diff --git a/.github/workflows/deploy-sync-test.yaml b/.github/workflows/deploy-sync-test.yaml
--- a/.github/workflows/deploy-sync-test.yaml
+++ b/.github/workflows/deploy-sync-test.yaml
@@ -118,45 +118,35 @@ jobs:
                 }
               ]
             }')
-
           jobId=$(echo $JOB_ID | jq -r '.jobId')
           echo "job_id=$jobId" >> $GITHUB_OUTPUT
-
       - name: Wait for Job Completion
         env:
           JOB_ID: ${{ steps.submit-job.outputs.job_id }}
         run: |
-            TIME_OUT=15
-            JOB_ID=${{ env.JOB_ID }}
-            count=0
-
-            while true; do
-              JOB_STATUS=$(aws batch describe-jobs --jobs $JOB_ID --query 'jobs[0].status' --output text)
-
-              if [ "$JOB_STATUS" == "SUCCEEDED" ] || [ "$JOB_STATUS" == "FAILED" ]; then
-                echo "Final job status: $JOB_STATUS"
-                break
-              fi
-
-              echo "Job status: $JOB_STATUS"
-
-              ((TIME_OUT++))
-
-              if [ $count -ge $TIME_OUT ]; then
-                echo "Batch JOB with id=${{ env.JOB_ID }} timout. Exiting."
-                exit 1
-              fi
-
-              sleep 60
-            done
-
-            if [ "$JOB_STATUS" == "FAILED" ]; then
-              echo "AWS Batch job failed"
+          TIME_OUT=15
+          JOB_ID=${{ env.JOB_ID }}
+          count=0
+          while true; do
+            JOB_STATUS=$(aws batch describe-jobs --jobs $JOB_ID --query 'jobs[0].status' --output text)
+            if [ "$JOB_STATUS" == "SUCCEEDED" ] || [ "$JOB_STATUS" == "FAILED" ]; then
+              echo "Final job status: $JOB_STATUS"
+              break
+            fi
+            echo "Job status: $JOB_STATUS"
+            ((TIME_OUT++))
+            if [ $count -ge $TIME_OUT ]; then
+              echo "Batch JOB with id=${{ env.JOB_ID }} timout. Exiting."
               exit 1
             fi
-
+            sleep 60
+          done
+          if [ "$JOB_STATUS" == "FAILED" ]; then
+            echo "AWS Batch job failed"
+            exit 1
+          fi
   upload-batch-report:
-    name: Upload Sync Report to GitHub
+    name: upload sync report to github
     needs: run-sync-batch
     runs-on: ubuntu-latest
     steps:
@@ -167,56 +157,46 @@ jobs:
           aws-region: ${{ env.AWS_REGION }}
 
       - name: Download Allure Report from S3
+        env:
+          JOB_ID: ${{ needs.run-sync-batch.outputs.job_id }}
+          BUCKET_NAME: "devapp-olcs-pri-olcs-autotest-s3"
+          BUCKET_KEY: "vol-functional-tests"
         run: |
           mkdir -p ./upload/${{ inputs.build_id }}
           aws s3api get-object \
-            --bucket "devapp-olcs-pri-olcs-autotest-s3" \
-            --key "vol-functional-tests/${{ inputs.build_id }}/${{ env.REPORT_NAME }}" \
-            "./upload/${{ inputs.build_id }}/${{ env.REPORT_NAME }}"
-
+          --bucket ${{ env.BUCKET_NAME }} \
+          --key "${{ env.BUCKET_KEY }}/${{ inputs.build_id }}/${{ env.REPORT_NAME }}" \
+          "./upload/${{ inputs.build_id }}/${{ env.REPORT_NAME }}"
       - name: Install Allure CLI
         uses: actions/setup-node@v2
         with:
-         node-version: '14'
+          node-version: '14'
       - run: npm install -g allure-commandline --save-dev
 
       - name: Unzip Allure Report
         run: |
           unzip ./upload/${{ inputs.build_id }}/${{ env.REPORT_NAME }} -d ./upload/${{ inputs.build_id }}/allure-report
-
-      - name: Debug Output - Contents of report directory
-        run: |
-          ls -l ./upload/${{ inputs.build_id }}/allure-report
-          ls -l ./upload/${{ inputs.build_id }}/allure-report/data
-           ls -l ./upload/${{ inputs.build_id }}/allure-report/history
-           ls -l ./upload/${{ inputs.build_id }}/allure-report/widgets
-
       - name: Generate Allure Report
         run: |
           allure generate ./upload/${{ inputs.build_id }}/allure-report --clean -o ./upload/${{ inputs.build_id }}/allure-report
-
-      - name: Verify Generated Report
+      - name: Copy Allure History
+        if: always()
         run: |
-          if ! grep -q '"total":0' ./upload/${{ inputs.build_id }}/allure-report/widgets/summary.json; then
-            echo "Allure report contains test cases."
-          else
-            echo "Allure report shows 0 test cases. Exiting with error."
-            exit 1
-          fi
+          mkdir -p ./upload/${{ inputs.build_id }}/allure-report/history
+          cp -r gh-pages/allure-history/* ./upload/${{ inputs.build_id }}/allure-report/history || true
+      - name: Upload Allure Report to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_branch: gh-pages
+          publish_dir: ./upload/${{ inputs.build_id }}/allure-report
 
-      - name: Upload Allure Report to GitHub Pages and S3
+      - name: Upload Unzipped Allure Report to S3
+        env:
+          BUCKET_NAME: "devapp-olcs-pri-olcs-autotest-s3"
+          BUCKET_KEY: "vol-functional-tests"
         run: |
-          # GitHub Pages
-          mkdir -p ./upload/${{ inputs.build_id }}/allure-report
-          cp -r ./upload/${{ inputs.build_id }}/allure-report/* ./upload/${{ inputs.build_id }}/allure-report/
-          # S3
-          aws s3 sync ./upload/${{ inputs.build_id }}/allure-report s3://devapp-olcs-pri-olcs-autotest-s3/vol-functional-tests/${{ inputs.build_id }}/allure-report
-
-      - name: Echo Allure Report URL
-        run: |
-          REPORT_URL="https://devapp-olcs-pri-olcs-autotest-s3.s3.amazonaws.com/vol-functional-tests/${{ inputs.build_id }}/allure-report/index.html"
-          echo "Allure Report URL: $REPORT_URL"
-
+          aws s3 sync ./upload/${{ inputs.build_id }}/allure-report s3://${{ env.BUCKET_NAME }}/${{ env.BUCKET_KEY }}/${{ inputs.build_id }}/allure-report
       - name: Job Succeeded
         if: success()
         run: echo "AWS Batch job completed successfully!"
